// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: root.sql

package models

import (
	"context"
)

const getJournalEntries = `-- name: GetJournalEntries :many
select id, title, date, body
from journal_entries
`

func (q *Queries) GetJournalEntries(ctx context.Context) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, getJournalEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Date,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
