// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: debts.sql

package models

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
insert into debts (
        id,
        amount,
        currency,
        contact_id
    )
values ($1, $2, $3, $4)
returning id
`

type CreateDebtParams struct {
	ID        int32
	Amount    float64
	Currency  string
	ContactID int32
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createDebt,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.ContactID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
