// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: debts.sql

package models

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
with contact as (
    select id
    from contacts
    where contacts.id = $1
        and namespace = $2
),
insertion as (
    insert into debts (amount, currency, contact_id)
    select $3,
        $4,
        $1
    from contact
    where exists (
            select 1
            from contact
        )
    returning debts.id
)
select id
from insertion
`

type CreateDebtParams struct {
	ID        int32
	Namespace string
	Amount    float64
	Currency  string
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createDebt,
		arg.ID,
		arg.Namespace,
		arg.Amount,
		arg.Currency,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
