// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package models

import (
	"time"
)

type Contact struct {
	ID        int32
	FirstName string
	LastName  string
	Nickname  string
	Email     string
	Pronouns  string
	Namespace string
}

type Debt struct {
	ID          int32
	Amount      float64
	Currency    string
	ContactID   int32
	Description string
}

type JournalEntry struct {
	ID        int32
	Title     string
	Date      time.Time
	Body      string
	Rating    int32
	Namespace string
}
